- eigen values
- l2 norm
- bounds of l2 norm
- pd test
- inverse of matrix
- determinant
- rank 
- LU decomposition
- SVD
- Sympy 
- concatenate matrices
- Gram Schimdt

In [1]:
import numpy as np
from numpy import linalg as LA

Eigen Value Function

In [1]:
def find_eigenValues(A,lis=False):
    if lis:
        A = np.array(A)
    w, v = LA.eig(A)
#     print('matrix: ',A)
#     print('values: ',w)
#     print('vectors: ', v)
    return w, v
    

In [4]:
matrix = [[6,18],[18,54]]
vals, vectors = find_eigenValues(matrix,lis=True)

L2 Norm

In [5]:
v = [1/2.0,1/2.0,1]
n = LA.norm(v)
print(f'norm {n}')
print(f'normalised v: {v/n}')

norm 1.224744871391589
normalised v: [0.40824829 0.40824829 0.81649658]


Bounds for L2 L1 norm

In [5]:
a = np.arange(9) - 4

In [6]:
print(a)

[-4 -3 -2 -1  0  1  2  3  4]


In [7]:
L2 = LA.norm(a)
print('L2 norm: ', L2)

L2 norm:  7.745966692414834


In [8]:
L1 = LA.norm(a,ord=1)
print('L1 norm: ',L1)

L1 norm:  20.0


In [9]:
root_a = np.sqrt(len(a))
print("upper bound: ",root_a*L2)

upper bound:  23.237900077244504


Positive Definite Test

In [6]:
def test_pd(A):
    A = np.array(A)
    print(A)
    if np.array_equal(A, A.T):
        try:
            LA.cholesky(A)
            return True
        except:
            return False
    else:
        return False

In [7]:
test_pd([[1,2],[2,5]])

[[1 2]
 [2 5]]


True

In [8]:
x = 3
B = [[1,2,-1,-2],
     [2,5,-2,-5],
     [-1,-2,x*1,x*2],
     [-2,-5,x*2,x*5]
    ]

In [9]:
test_pd(B)

[[ 1  2 -1 -2]
 [ 2  5 -2 -5]
 [-1 -2  3  6]
 [-2 -5  6 15]]


True

Inverse of Matrix

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,9],[9,3]])

In [14]:
C = A+B
C_inv = LA.inv(C)
A_inv = LA.inv(A)
B_inv = LA.inv(B)
D = A_inv + B_inv
print(f'C_inv\n{C_inv}') #(A + B)^-1
print(f'D\n{D}') #A-1 + B-1

C_inv
[[-0.07216495  0.11340206]
 [ 0.12371134 -0.05154639]]
D
[[-2.04347826  1.13043478]
 [ 1.63043478 -0.55797101]]


Determinant

In [15]:
a = np.array([[1,1,0,0],
               [0,0,1,1],
              [-1,0,-1,0],
              [0,-1,0,-1]
             ])
LA.det(a)

0.0

Matrix Rank

In [16]:
from numpy.linalg import matrix_rank

In [17]:
m = np.array([[2,2,7],
              [3,6,12],
              [3,4,11]
             ])

In [18]:
r1 = LA.matrix_rank(m)
print(r1)

2


LU decomposition

In [19]:
import scipy.linalg as SC_LA

In [20]:
mat = np.array([[2,5,6],
                [0,1,5],
                [3,9,4]
               ])

Matrix multiplication

In [21]:
def multiply_mat(A,B,lis=False):
    print('multiplying: ')
    print(A)
    print(B)
    print('-----')
    if lis:
        A = np.array(A)
        B = np.array(B)
    C = np.matmul(A,B)
    print('result: \n{}\n===='.format(C))
    return C

In [22]:
A = np.array([[2,1,1],[-5,-3,0],[1,1,-1]])
# B = np.array([[2,5,6],[0,1,5],[0,0,-25/2]])

In [23]:
C = multiply_mat(A.T,A)

multiplying: 
[[ 2 -5  1]
 [ 1 -3  1]
 [ 1  0 -1]]
[[ 2  1  1]
 [-5 -3  0]
 [ 1  1 -1]]
-----
result: 
[[30 18  1]
 [18 11  0]
 [ 1  0  2]]
====


In [25]:
vals_C , vectors_C = find_eigenValues(C)

SVD decomposition

In [26]:
u, s, vh = LA.svd(A, full_matrices=False)
print(A)
print(u)
print(s)
print(vh)

[[ 2  1  1]
 [-5 -3  0]
 [ 1  1 -1]]
[[-0.35204116 -0.66272935  0.66095146]
 [ 0.91184354 -0.08349001  0.40195867]
 [-0.21120697  0.74419031  0.6336974 ]]
[6.39312147 1.45479812 0.10751878]
[[-0.85631205 -0.51598875 -0.02202902]
 [-0.11260554  0.22816293 -0.96708928]
 [-0.50403339  0.82564962  0.25348186]]


In [27]:
S = np.array([[6.393,0,0],
              [0,1.471,0],
              [0,0,0.107]]
            )

In [28]:
x = multiply_mat(u,S)
print(multiply_mat(x,vh))

multiplying: 
[[-0.35204116 -0.66272935  0.66095146]
 [ 0.91184354 -0.08349001  0.40195867]
 [-0.21120697  0.74419031  0.6336974 ]]
[[6.393 0.    0.   ]
 [0.    1.471 0.   ]
 [0.    0.    0.107]]
-----
result: 
[[-2.25059911 -0.97487488  0.07072181]
 [ 5.82941575 -0.12281381  0.04300958]
 [-1.35024613  1.09470395  0.06780562]]
====
multiplying: 
[[-2.25059911 -0.97487488  0.07072181]
 [ 5.82941575 -0.12281381  0.04300958]
 [-1.35024613  1.09470395  0.06780562]]
[[-0.85631205 -0.51598875 -0.02202902]
 [-0.11260554  0.22816293 -0.96708928]
 [-0.50403339  0.82564962  0.25348186]]
-----
result: 
[[ 2.00134531e+00  9.97244941e-01  1.01029622e+00]
 [-4.99964773e+00 -3.00042365e+00  1.25775901e-03]
 [ 9.98786014e-01  1.00246636e+00 -1.01174436e+00]]
====
[[ 2.00134531e+00  9.97244941e-01  1.01029622e+00]
 [-4.99964773e+00 -3.00042365e+00  1.25775901e-03]
 [ 9.98786014e-01  1.00246636e+00 -1.01174436e+00]]


Simplify variables

In [2]:
import sympy as sym

In [3]:
a = sym.Symbol('a')
p1 = sym.Symbol('p1')
p2 = sym.Symbol('p2')
q1 = sym.Symbol('q1')
q2 = sym.Symbol('q2')

In [4]:
y = -(a*(p1-q1)+q1)**2 + a*(p2-q2) + q2 - 1

In [13]:
sym.simplify( y ,ratio=oo)

a*(p2 - q2) + q2 - (a*(p1 - q1) + q1)**2 - 1

In [33]:
x = sym.Symbol('x')
c = sym.Symbol('c')
d = sym.Symbol('d')

In [34]:
sym.simplify( ((8-2*d)/5)**2 + ((d-4)/5)**2 + 25 )

(d - 4)**2/5 + 25

Dot product

In [37]:
a = [1,2,0]
b = [2,37/3,5]
np.dot(a,b)

26.666666666666668

Concatenate matrices

In [29]:
import random
random.seed(42)

In [45]:
np.random.seed(42)
u1 = np.array(np.random.randint(0,4,3)).reshape(-1,1)
u2 = np.array(np.random.randint(0,4,3)).reshape(-1,1)
u3 = np.array(np.random.randint(0,4,3)).reshape(-1,1)

In [46]:
u1.shape

(3, 1)

In [47]:
U = np.concatenate((u1,u2,u3),axis=1)
print(U)

[[2 2 0]
 [3 2 0]
 [0 3 2]]


projection

In [51]:
def projection(u,v):
    num = np.dot(u,v)
    den = np.dot(u,u)
    ratio = num/den
    return ratio*v

In [52]:
def gramSchimdt(v1,v2,v3):
    u1 = v1
    u2 = v2 - projection(u1, v2)
    u3 = v3 - projection(u1, v3) - projection(u2,v3)
    return u1,u2,u3

In [122]:
v1 = np.array([1,2,0])
def makeV2(i):
    v2 = np.array([2,i,5])
    return v2
v3 = np.array([0,5,3])

In [117]:
def findUnitVector(u):
    return u/LA.norm(u)

In [123]:
def gramS(v1,v2,v3):
    for i in range(-10,10,1):
        v2 = makeV2(i)
        print('v2: {}'.format(v2))
        u1,u2,u3 = gramSchimdt(v1,v2,v3)
        u1 = findUnitVector(u1)
        u2 = findUnitVector(u2)
        u3 = findUnitVector(u3)
        
        print(u1,u2,u3)
        print('<--------->')

In [124]:
gramS(v1,v2,v3)

v2: [  2 -10   5]
[0.4472136  0.89442719 0.        ] [ 0.17609018 -0.88045091  0.44022545] [ 0.         -0.85749293 -0.51449576]
<--------->
v2: [ 2 -9  5]
[0.4472136  0.89442719 0.        ] [ 0.19069252 -0.85811633  0.47673129] [ 0.         -0.85749293 -0.51449576]
<--------->
v2: [ 2 -8  5]
[0.4472136  0.89442719 0.        ] [ 0.20739034 -0.82956136  0.51847585] [ 0.         -0.85749293 -0.51449576]
<--------->
v2: [ 2 -7  5]
[0.4472136  0.89442719 0.        ] [ 0.22645541 -0.79259392  0.56613852] [ 0.         -0.85749293 -0.51449576]
<--------->
v2: [ 2 -6  5]
[0.4472136  0.89442719 0.        ] [ 0.24806947 -0.74420841  0.62017367] [ 0.         -0.85749293 -0.51449576]
<--------->
v2: [ 2 -5  5]
[0.4472136  0.89442719 0.        ] [ 0.27216553 -0.68041382  0.68041382] [ 0.         -0.85749293 -0.51449576]
<--------->
v2: [ 2 -4  5]
[0.4472136  0.89442719 0.        ] [ 0.2981424  -0.59628479  0.74535599] [ 0.         -0.85749293 -0.51449576]
<--------->
v2: [ 2 -3  5]
[0.4472136  0.89